[package]
name = "auth-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
# serde_json is just for the example, not required in general
serde_json = "1.0"
